# Generated by Django 5.1.1 on 2024-10-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Select a Language of this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catlog.language'),
        ),
    ]
