# Generated by Django 5.1.1 on 2024-10-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
