# Generated by Django 5.1.1 on 2024-10-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('staff_user', 'Staff user'))},
        ),
    ]
